/*
 * This source file was generated by the Gradle 'init' task
 */
package taller1_nastul_valdez_cifuentes;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       
    }
}
