//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.11
//
// <auto-generated>
//
// Generated from file `ApexStore.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ApexStoreIce;

/** @hidden */
public class _ServicioCheckoutIPrxI extends com.zeroc.Ice._ObjectPrxI implements ServicioCheckoutIPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
