//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.11
//
// <auto-generated>
//
// Generated from file `ApexStore.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ApexStoreIce;

public class ResultadoPago implements java.lang.Cloneable,
                                      java.io.Serializable
{
    public String ordenId;

    public boolean exito;

    public String codigoTransaccion;

    public String mensaje;

    public ResultadoPago()
    {
        this.ordenId = "";
        this.codigoTransaccion = "";
        this.mensaje = "";
    }

    public ResultadoPago(String ordenId, boolean exito, String codigoTransaccion, String mensaje)
    {
        this.ordenId = ordenId;
        this.exito = exito;
        this.codigoTransaccion = codigoTransaccion;
        this.mensaje = mensaje;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ResultadoPago r = null;
        if(rhs instanceof ResultadoPago)
        {
            r = (ResultadoPago)rhs;
        }

        if(r != null)
        {
            if(this.ordenId != r.ordenId)
            {
                if(this.ordenId == null || r.ordenId == null || !this.ordenId.equals(r.ordenId))
                {
                    return false;
                }
            }
            if(this.exito != r.exito)
            {
                return false;
            }
            if(this.codigoTransaccion != r.codigoTransaccion)
            {
                if(this.codigoTransaccion == null || r.codigoTransaccion == null || !this.codigoTransaccion.equals(r.codigoTransaccion))
                {
                    return false;
                }
            }
            if(this.mensaje != r.mensaje)
            {
                if(this.mensaje == null || r.mensaje == null || !this.mensaje.equals(r.mensaje))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::ApexStoreIce::ResultadoPago");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, ordenId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, exito);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, codigoTransaccion);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, mensaje);
        return h_;
    }

    public ResultadoPago clone()
    {
        ResultadoPago c = null;
        try
        {
            c = (ResultadoPago)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.ordenId);
        ostr.writeBool(this.exito);
        ostr.writeString(this.codigoTransaccion);
        ostr.writeString(this.mensaje);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.ordenId = istr.readString();
        this.exito = istr.readBool();
        this.codigoTransaccion = istr.readString();
        this.mensaje = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ResultadoPago v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ResultadoPago ice_read(com.zeroc.Ice.InputStream istr)
    {
        ResultadoPago v = new ResultadoPago();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ResultadoPago> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ResultadoPago v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<ResultadoPago> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(ResultadoPago.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ResultadoPago _nullMarshalValue = new ResultadoPago();

    /** @hidden */
    public static final long serialVersionUID = 1748584156L;
}
