//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.11
//
// <auto-generated>
//
// Generated from file `ApexStore.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ApexStoreIce;

public class SolicitudPago implements java.lang.Cloneable,
                                      java.io.Serializable
{
    public String ordenId;

    public double monto;

    public String metodoPago;

    public String detallesCliente;

    public SolicitudPago()
    {
        this.ordenId = "";
        this.metodoPago = "";
        this.detallesCliente = "";
    }

    public SolicitudPago(String ordenId, double monto, String metodoPago, String detallesCliente)
    {
        this.ordenId = ordenId;
        this.monto = monto;
        this.metodoPago = metodoPago;
        this.detallesCliente = detallesCliente;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        SolicitudPago r = null;
        if(rhs instanceof SolicitudPago)
        {
            r = (SolicitudPago)rhs;
        }

        if(r != null)
        {
            if(this.ordenId != r.ordenId)
            {
                if(this.ordenId == null || r.ordenId == null || !this.ordenId.equals(r.ordenId))
                {
                    return false;
                }
            }
            if(this.monto != r.monto)
            {
                return false;
            }
            if(this.metodoPago != r.metodoPago)
            {
                if(this.metodoPago == null || r.metodoPago == null || !this.metodoPago.equals(r.metodoPago))
                {
                    return false;
                }
            }
            if(this.detallesCliente != r.detallesCliente)
            {
                if(this.detallesCliente == null || r.detallesCliente == null || !this.detallesCliente.equals(r.detallesCliente))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::ApexStoreIce::SolicitudPago");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, ordenId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, monto);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, metodoPago);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, detallesCliente);
        return h_;
    }

    public SolicitudPago clone()
    {
        SolicitudPago c = null;
        try
        {
            c = (SolicitudPago)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.ordenId);
        ostr.writeDouble(this.monto);
        ostr.writeString(this.metodoPago);
        ostr.writeString(this.detallesCliente);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.ordenId = istr.readString();
        this.monto = istr.readDouble();
        this.metodoPago = istr.readString();
        this.detallesCliente = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, SolicitudPago v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public SolicitudPago ice_read(com.zeroc.Ice.InputStream istr)
    {
        SolicitudPago v = new SolicitudPago();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<SolicitudPago> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, SolicitudPago v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<SolicitudPago> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(SolicitudPago.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final SolicitudPago _nullMarshalValue = new SolicitudPago();

    /** @hidden */
    public static final long serialVersionUID = 495991151L;
}
